version: "3.9"
services:
  web:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    depends_on:
      - api
    security_opt:
      - 'no-new-privileges:true'

  api:
    build: ./backend
    volumes:
      - ./backend:/code
    depends_on:
      - mongodb
    environment:
      MONGODB_DATABASE: flaskdb
      MONGODB_USERNAME: flaskuser
      MONGODB_PASSWORD: flaskuser
      MONGODB_HOSTNAME: mongodb
      FLASK_ENV: development


  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: flaskuser
      MONGO_INITDB_ROOT_PASSWORD: flaskuser
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    ports:
      - "27017:27017"

  notification:
    build: ./notifications
    volumes:
      - ./notifications:/code
    depends_on:
      - mongodb
    environment:
      MONGODB_DATABASE: flaskdb
      MONGODB_USERNAME: flaskuser
      MONGODB_PASSWORD: flaskuser
      MONGODB_HOSTNAME: mongodb
      